[theme]
base = "light"
primaryColor = "#6C63FF"              # Vibrant Purple
backgroundColor = "#EAF6FF"           # Light Blue
secondaryBackgroundColor = "#FFFFFF"  # White for contrast
textColor = "#2B2D42"                 # Deep bluish-gray
font = "Helvetica"

[server]
headless = true
port = 8501
runOnSave = true